jobs:
  deploy:
    working_directory: ~/repo/azure-function-app/
    executor: python/default
    steps:
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Install Azure Functions Core Tools
          command: sudo apt-get update && sudo apt-get install azure-functions-core-tools-4
      - run:
          name: Deploy to Azure Function App
          command: func azure functionapp publish $FUNCTION_APP_NAME --python

orbs:
  azure-cli: circleci/azure-cli@1.0.0
  python: circleci/python@1.3.0
version: 2.1
workflows:
  login-workflow:
    jobs:
      - deploy