jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Install Azure Functions Core Tools
          command: |
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
            sudo apt-get update
            sudo apt-get install azure-functions-core-tools-4
      - run:
          name: Deploy to Azure Function App
          command: |
            CLI_DEBUG=1 func azure functionapp publish $FUNCTION_APP_NAME --python
            az functionapp config appsettings set --name $FUNCTION_APP_NAME --resource-group $FUNCTION_APP_NAME_RESOURCE_GROUP --settings OPENWEATHERMAP_API_KEY=$OPENWEATHERMAP_API_KEY

orbs:
  azure-cli: circleci/azure-cli@1.0.0
  python: circleci/python@1.2.0
version: 2.1
workflows:
  login-workflow:
    jobs:
      - deploy